export const APPLICATION_STATUS = {
  APPLIED: "APPLIED",
  SHORTLISTED: "SHORTLISTED",
  SELECTED: "SELECTED",
  REJECTED: "REJECTED",
  WITHDRAWN: "WITHDRAWN",
};

export const APPLICATION_STATUS_LABELS = {
  [APPLICATION_STATUS.APPLIED]: "Applied",
  [APPLICATION_STATUS.SHORTLISTED]: "Shortlisted",
  [APPLICATION_STATUS.SELECTED]: "Selected",
  [APPLICATION_STATUS.REJECTED]: "Rejected",
  [APPLICATION_STATUS.WITHDRAWN]: "Withdrawn",
};

export const APPLICATION_STATUS_COLORS = {
  [APPLICATION_STATUS.APPLIED]: "info",
  [APPLICATION_STATUS.SHORTLISTED]: "warning",
  [APPLICATION_STATUS.SELECTED]: "success",
  [APPLICATION_STATUS.REJECTED]: "error",
  [APPLICATION_STATUS.WITHDRAWN]: "default",
};
