export const CERTIFICATE_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  ISSUED: "ISSUED",
};

export const CERTIFICATE_STATUS_LABELS = {
  [CERTIFICATE_STATUS.PENDING]: "Pending",
  [CERTIFICATE_STATUS.APPROVED]: "Approved",
  [CERTIFICATE_STATUS.REJECTED]: "Rejected",
  [CERTIFICATE_STATUS.ISSUED]: "Issued",
};

export const CERTIFICATE_STATUS_COLORS = {
  [CERTIFICATE_STATUS.PENDING]: "warning",
  [CERTIFICATE_STATUS.APPROVED]: "info",
  [CERTIFICATE_STATUS.REJECTED]: "error",
  [CERTIFICATE_STATUS.ISSUED]: "success",
};
