export const NOTIFICATION_TYPES = {
  APPLICATION_UPDATE: "APPLICATION_UPDATE",
  CERTIFICATE_UPDATE: "CERTIFICATE_UPDATE",
  JOB_POSTED: "JOB_POSTED",
  SESSION_SCHEDULED: "SESSION_SCHEDULED",
  NEWS: "NEWS",
  GENERAL: "GENERAL",
};

export const NOTIFICATION_TYPE_LABELS = {
  [NOTIFICATION_TYPES.APPLICATION_UPDATE]: "Application Update",
  [NOTIFICATION_TYPES.CERTIFICATE_UPDATE]: "Certificate Update",
  [NOTIFICATION_TYPES.JOB_POSTED]: "Job Posted",
  [NOTIFICATION_TYPES.SESSION_SCHEDULED]: "Session Scheduled",
  [NOTIFICATION_TYPES.NEWS]: "News",
  [NOTIFICATION_TYPES.GENERAL]: "General",
};
