export const ConversationState = {

    RESUME_TYPE: "RESUME_TYPE",

    PERSONAL_INFO: "PERSONAL_INFO",

    EDUCATION: "EDUCATION",

    EXPERIENCE: "EXPERIENCE",

    PROJECTS: "PROJECTS",
    PROJECT_CONFIRMATION:
        "PROJECT_CONFIRMATION",

    SKILLS: "SKILLS",

    CERTIFICATES: "CERTIFICATES",
    CERTIFICATE_CONFIRMATION:
        "CERTIFICATE_CONFIRMATION",

    ACHIEVEMENTS: "ACHIEVEMENTS",
    ACHIEVEMENT_CONFIRMATION:
        "ACHIEVEMENT_CONFIRMATION",

    TARGET_COMPANY: "TARGET_COMPANY",

    JOB_DESCRIPTION: "JOB_DESCRIPTION",

    GENERATE_RESUME: "GENERATE_RESUME",

};