export const ConversationState = {

    RESUME_TYPE: "RESUME_TYPE",

    PERSONAL_INFO: "PERSONAL_INFO",

    EDUCATION: "EDUCATION",

    EXPERIENCE: "EXPERIENCE",
    PROJECT_AVAILABILITY: "PROJECT_AVAILABILITY",

    PROJECTS: "PROJECTS",
    PROJECT_CONFIRMATION:
        "PROJECT_CONFIRMATION",

    SKILLS: "SKILLS",
    CERTIFICATE_AVAILABILITY: "CERTIFICATE_AVAILABILITY",
    CERTIFICATES: "CERTIFICATES",
    CERTIFICATE_CONFIRMATION:
        "CERTIFICATE_CONFIRMATION",
    ACHIEVEMENT_AVAILABILITY: "ACHIEVEMENT_AVAILABILITY",
    ACHIEVEMENTS: "ACHIEVEMENTS",
    ACHIEVEMENT_CONFIRMATION:
        "ACHIEVEMENT_CONFIRMATION",

    TARGET_COMPANY: "TARGET_COMPANY",

    JOB_DESCRIPTION: "JOB_DESCRIPTION",

    GENERATE_RESUME: "GENERATE_RESUME",

};